export const US_STOCKS = [
  "MMM","AOS","ABT","ABBV","ACN","ADBE","AMD","AES","AFL","A","APD","ABNB","AKAM","ALB","ARE","ALGN","ALLE","LNT","ALL","GOOGL","GOOG","MO","AMZN","AMCR","AEE","AEP","AXP","AIG","AMT","AWK","AMP","AME","AMGN","APH","ADI","AON","APA","APO","AAPL","AMAT","APP","APTV","ACGL","ADM","ARES","ANET","AJG","AIZ","T","ATO","ADSK","ADP","AZO","AVB","AVY","AXON","BKR","BALL","BAC","BAX","BDX","BBY","TECH","BIIB","BLK","BX","BNY","BA","BKNG","BSX","BMY","AVGO","BR","BRO","BLDR","BG","BXP","CHRW","CDNS","CPT","CPB","COF","CAH","CCL","CARR","CVNA","CASY","CAT","CBOE","CBRE","CDW","COR","CNC","CNP","CF","CRL","SCHW","CHTR","CVX","CMG","CB","CHD","CIEN","CI","CINF","CTAS","CSCO","C","CFG","CLX","CME","CMS","KO","CTSH","COHR","COIN","CL","CMCSA","FIX","CAG","COP","ED","STZ","CEG","COO","CPRT","GLW","CPAY","CTVA","CSGP","COST","CRH","CRWD","CCI","CSX","CMI","CVS","DHR","DRI","DDOG","DVA","DECK","DE","DELL","DAL","DVN","DXCM","FANG","DLR","DG","DLTR","D","DPZ","DASH","DOV","DOW","DHI","DTE","DUK","DD","ETN","EBAY","SATS","ECL","EIX","EW","EA","ELV","EME","EMR","ETR","EOG","EPAM","EQT","EFX","EQIX","EQR","ERIE","ESS","EL","EG","EVRG","ES","EXC","EXE","EXPE","EXPD","EXR","XOM","FFIV","FDS","FICO","FAST","FRT","FDX","FIS","FITB","FSLR","FE","FISV","F","FTNT","FTV","FOXA","FOX","BEN","FCX","GRMN","IT","GE","GEHC","GEV","GEN","GNRC","GD","GIS","GM","GPC","GILD","GPN","GL","GDDY","GS","HAL","HIG","HAS","HCA","DOC","HSIC","HSY","HPE","HLT","HD","HON","HRL","HST","HWM","HPQ","HUBB","HUM","HBAN","HII","IBM","IEX","IDXX","ITW","INCY","IR","PODD","INTC","IBKR","ICE","IFF","IP","INTU","ISRG","IVZ","INVH","IQV","IRM","JBHT","JBL","JKHY","J","JNJ","JCI","JPM","KVUE","KDP","KEY","KEYS","KMB","KIM","KMI","KKR","KLAC","KHC","KR","LHX","LH","LRCX","LVS","LDOS","LEN","LII","LLY","LIN","LYV","LMT","L","LOW","LULU","LITE","LYB","MTB","MPC","MAR","MRSH","MLM","MAS","MA","MKC","MCD","MCK","MDT","MRK","META","MET","MTD","MGM","MCHP","MU","MSFT","MAA","MRNA","TAP","MDLZ","MPWR","MNST","MCO","MS","MOS","MSI","MSCI","NDAQ","NTAP","NFLX","NEM","NWSA","NWS","NEE","NKE","NI","NDSN","NSC","NTRS","NOC","NCLH","NRG","NUE","NVDA","NVR","NXPI","ORLY","OXY","ODFL","OMC","ON","OKE","ORCL","OTIS","PCAR","PKG","PLTR","PANW","PSKY","PH","PAYX","PYPL","PNR","PEP","PFE","PCG","PM","PSX","PNW","PNC","POOL","PPG","PPL","PFG","PG","PGR","PLD","PRU","PEG","PTC","PSA","PHM","PWR","QCOM","DGX","Q","RL","RJF","RTX","O","REG","REGN","RF","RSG","RMD","RVTY","HOOD","ROK","ROL","ROP","ROST","RCL","SPGI","CRM","SNDK","SBAC","SLB","STX","SRE","NOW","SHW","SPG","SWKS","SJM","SW","SNA","SOLV","SO","LUV","SWK","SBUX","STT","STLD","STE","SYK","SMCI","SYF","SNPS","SYY","TMUS","TROW","TTWO","TPR","TRGP","TGT","TEL","TDY","TER","TSLA","TXN","TPL","TXT","TMO","TJX","TKO","TTD","TSCO","TT","TDG","TRV","TRMB","TFC","TYL","TSN","USB","UBER","UDR","ULTA","UNP","UAL","UPS","URI","UNH","UHS","VLO","VEEV","VTR","VLTO","VRSN","VRSK","VZ","VRTX","VRT","VTRS","VICI","V","VST","VMC","WRB","GWW","WAB","WMT","DIS","WBD","WM","WAT","WEC","WFC","WELL","WST","WDC","WY","WSM","WMB","WTW","WDAY","WYNN","XEL","XYL","YUM","ZBRA","ZBH","ZTS"
];

export const HALAL_US_STOCKS = [
  "MMM","AOS","ABBV","ACN","ADBE","AMD","AES","APD","ABNB","AKAM","ALB","ARE","ALLE","LNT","GOOGL","GOOG","AMZN","AMCR","AEE","AEP","AMT","AWK","AME","AMGN","APH","ADI","APA","APO","AAPL","AMAT","APP","APTV","ACGL","ADM","ARES","ANET","T","ATO","ADSK","ADP","AZO","AVB","AVY","AXON","BKR","BALL","BAX","BDX","BBY","BIIB","BX","BNY","BKNG","BMY","AVGO","BLDR","BG","BXP","CHRW","CDNS","CPT","CPB","CAH","CCL","CARR","CVNA","CASY","CAT","CBRE","CDW","COR","CNC","CNP","CF","CHTR","CVX","CMG","CHD","CIEN","CI","CTAS","CSCO","CLX","CMS","KO","CTSH","COHR","COIN","CL","CMCSA","FIX","CAG","COP","ED","CEG","CPRT","GLW","CPAY","CTVA","CSGP","COST","CRH","CRWD","CCI","CSX","CMI","CVS","DRI","DDOG","DVA","DECK","DE","DELL","DAL","DVN","FANG","DLR","DG","DLTR","D","DPZ","DASH","DOV","DOW","DHI","DTE","DUK","DD","ETN","EBAY","SATS","ECL","EIX","EA","ELV","EME","EMR","ETR","EOG","EPAM","EQT","EFX","EQIX","EQR","ERIE","ESS","EL","EG","EVRG","ES","EXC","EXE","EXPE","EXPD","EXR","XOM","FFIV","FDS","FICO","FAST","FRT","FDX","FSLR","FE","FISV","F","FTNT","FTV","FOXA","FOX","FCX","GRMN","IT","GE","GEHC","GEV","GEN","GNRC","GIS","GM","GPC","GILD","GDDY","HAL","HAS","HCA","DOC","HSIC","HSY","HPE","HLT","HD","HON","HRL","HST","HWM","HPQ","HUBB","HUM","IBM","IEX","IDXX","ITW","INCY","IR","PODD","INTC","IFF","IP","INTU","ISRG","INVH","IRM","JBHT","JBL","J","JNJ","JCI","KVUE","KDP","KEYS","KMB","KIM","KMI","KKR","KLAC","KHC","KR","LHX","LH","LRCX","LVS","LDOS","LEN","LII","LLY","LIN","LYV","LOW","LULU","LITE","LYB","MPC","MAR","MRSH","MLM","MAS","MKC","MCD","MCK","MRK","META","MGM","MCHP","MU","MSFT","MAA","MRNA","MDLZ","MPWR","MNST","MOS","MSI","NTAP","NFLX","NEM","NWSA","NWS","NEE","NKE","NI","NDSN","NSC","NCLH","NRG","NUE","NVDA","NVR","NXPI","ORLY","OXY","ODFL","OMC","ON","OKE","ORCL","OTIS","PCAR","PKG","PLTR","PANW","PSKY","PH","PNR","PEP","PFE","PCG","PSX","PNW","PNC","POOL","PPG","PPL","PG","PLD","PEG","PTC","PSA","PHM","PWR","QCOM","DGX","Q","RL","RJF","O","REG","REGN","RSG","RMD","RVTY","ROK","ROL","ROP","ROST","RCL","CRM","SNDK","SBAC","SLB","STX","SRE","NOW","SHW","SPG","SWKS","SJM","SW","SNA","SOLV","SO","LUV","SWK","SBUX","STLD","SMCI","SNPS","SYY","TMUS","TTWO","TPR","TRGP","TGT","TEL","TDY","TER","TSLA","TXN","TPL","TXT","TJX","TKO","TTD","TSCO","TT","TDG","TRMB","TYL","TSN","USB","UBER","UDR","ULTA","UNP","UAL","UPS","URI","UNH","UHS","VLO","VEEV","VTR","VLTO","VRSN","VRSK","VZ","VRTX","VRT","VTRS","VICI","VST","VMC","GWW","WAB","WMT","DIS","WBD","WM","WEC","WELL","WDC","WY","WSM","WMB","WDAY","WYNN","XEL","XYL","YUM","ZBRA","ZTS","AP"
];

export const CRYPTO_SYMBOLS = [
  "BTC-USD", "ETH-USD", "USDT-USD", "BNB-USD", "SOL-USD", "STETH-USD", "USDC-USD", "XRP-USD",
  "DOGE-USD", "TON-USD", "ADA-USD", "SHIB-USD", "AVAX-USD", "TRX-USD", "DOT-USD", "BCH-USD",
  "LINK-USD", "MATIC-USD", "NEAR-USD", "LTC-USD", "ICP-USD", "LEO-USD", "DAI-USD", "UNI-USD",
  "APT-USD", "PEPE-USD", "FET-USD", "ETC-USD", "XLM-USD", "STX-USD", "MNT-USD", "FIL-USD",
  "IMX-USD", "RNDR-USD", "ATOM-USD", "ARB-USD", "INJ-USD", "TAO-USD", "OP-USD", "KAS-USD",
  "VET-USD", "WIF-USD", "FDUSD-USD", "GRT-USD", "THETA-USD", "MKR-USD", "HBAR-USD", "AR-USD",
  "LDO-USD", "MPEPE-USD", "FLOKI-USD", "CRO-USD", "BOND-USD", "TIA-USD", "ALGO-USD", "QNT-USD",
  "FTM-USD", "AAVE-USD", "FLOW-USD", "BSV-USD", "SEI-USD", "RUNE-USD", "JUP-USD", "EGLD-USD",
  "STRK-USD", "XEC-USD", "GALA-USD", "ROSE-USD", "BEAM-USD", "MBOX-USD", "XTZ-USD", "KCS-USD",
  "BTT-USD", "AXS-USD", "NEO-USD", "MINA-USD", "SAND-USD", "PYTH-USD", "WLD-USD", "CAKE-USD",
  "CHZ-USD", "MANA-USD", "ORDI-USD", "IOTA-USD", "ZEC-USD", "AERO-USD", "PENDLE-USD", "KLAY-USD",
  "CKB-USD", "ENJ-USD", "COMP-USD", "1INCH-USD", "CRV-USD", "DYDX-USD", "BAT-USD", "SUSHI-USD",
  "TWT-USD", "XMR-USD", "DASH-USD", "ZIL-USD"
];

export const NIFTY_500_SYMBOLS = [
  "3MINDIA.NS", "ABB.NS", "ACC.NS", "ACMESOLAR.NS", "AIAENG.NS", "APLAPOLLO.NS",
  "AWL.NS", "AARTIIND.NS", "ABBOTINDIA.NS", "ACE.NS", "ACUTAAS.NS", "ADANIENSOL.NS",
  "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "ATGL.NS", "ABFRL.NS",
  "ABLBL.NS", "ABREL.NS", "CPPLUS.NS", "AEGISLOG.NS", "AEGISVOPAK.NS", "AFCONS.NS",
  "AFFLE.NS", "AJANTPHARM.NS", "ALKEM.NS", "ARE&M.NS", "AMBER.NS", "AMBUJACEM.NS",
  "ANANTRAJ.NS", "ANTHEM.NS", "ANURAS.NS", "APARINDS.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS",
  "ASAHIINDIA.NS", "ASHOKLEY.NS", "ASIANPAINT.NS", "ASTERDM.NS", "ASTRAL.NS", "ATHERENERG.NS",
  "ATUL.NS", "AUROPHARMA.NS", "DMART.NS", "BEML.NS", "BLS.NS", "BAJAJ-AUTO.NS",
  "BALKRISIND.NS", "BALRAMCHIN.NS", "BATAINDIA.NS", "BAYERCROP.NS", "BELRISE.NS", "BERGEPAINT.NS",
  "BDL.NS", "BEL.NS", "BHARATFORG.NS", "BHEL.NS", "BPCL.NS", "BHARTIARTL.NS",
  "BHARTIHEXA.NS", "BIKAJI.NS", "BIOCON.NS", "BSOFT.NS", "BLUEDART.NS", "BLUEJET.NS",
  "BLUESTARCO.NS", "BBTC.NS", "BOSCHLTD.NS", "FIRSTCRY.NS", "BRIGADE.NS", "BRITANNIA.NS",
  "MAPMYINDIA.NS", "CCL.NS", "CESC.NS", "CGPOWER.NS", "CAPLIPOINT.NS", "CARBORUNIV.NS",
  "CARTRADE.NS", "CASTROLIND.NS", "CEATLTD.NS", "CEMPRO.NS", "CHALET.NS", "CHAMBLFERT.NS",
  "CHENNPETRO.NS", "CIPLA.NS", "CLEAN.NS", "COALINDIA.NS", "COCHINSHIP.NS", "COFORGE.NS",
  "COHANCE.NS", "COLPAL.NS", "CONCORDBIO.NS", "CONCOR.NS", "COROMANDEL.NS", "CRAFTSMAN.NS",
  "CROMPTON.NS", "CUMMINSIND.NS", "CYIENT.NS", "DCMSHRIRAM.NS", "DLF.NS", "DOMS.NS",
  "DABUR.NS", "DALBHARAT.NS", "DATAPATTNS.NS", "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS",
  "DEVYANI.NS", "DIVISLAB.NS", "DIXON.NS", "LALPATHLAB.NS", "DRREDDY.NS", "EIDPARRY.NS",
  "EIHOTEL.NS", "EICHERMOT.NS", "ELECON.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "EMCURE.NS",
  "EMMVEE.NS", "ENDURANCE.NS", "ENGINERSIN.NS", "ERIS.NS", "ESCORTS.NS", "ETERNAL.NS",
  "EXIDEIND.NS", "NYKAA.NS", "FACT.NS", "FINCABLES.NS", "FSL.NS", "FORCEMOT.NS",
  "FORTIS.NS", "GAIL.NS", "GVT&D.NS", "GMRAIRPORT.NS", "GABRIEL.NS", "GALLANTT.NS",
  "GRSE.NS", "GILLETTE.NS", "GLAND.NS", "GLAXO.NS", "GLENMARK.NS", "MEDANTA.NS",
  "GPIL.NS", "GODREJCP.NS", "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRAPHITE.NS",
  "GRASIM.NS", "GRAVITA.NS", "GESHIP.NS", "FLUOROCHEM.NS", "GMDCLTD.NS", "GSPL.NS",
  "HEG.NS", "HBLENGINE.NS", "HCLTECH.NS", "HFCL.NS", "HAVELLS.NS", "HEROMOTOCO.NS",
  "HEXT.NS", "HSCL.NS", "HINDALCO.NS", "HAL.NS", "HINDCOPPER.NS", "HINDPETRO.NS",
  "HINDUNILVR.NS", "HINDZINC.NS", "POWERINDIA.NS", "HONASA.NS", "HONAUT.NS", "HYUNDAI.NS",
  "IRB.NS", "IRCON.NS", "ITCHOTELS.NS", "ITI.NS", "INDGN.NS", "INDIACEM.NS",
  "INDIAMART.NS", "INDHOTEL.NS", "IOC.NS", "IRCTC.NS", "IGL.NS", "INDUSTOWER.NS",
  "NAUKRI.NS", "INFY.NS", "INOXWIND.NS", "INTELLECT.NS", "INDIGO.NS", "IGIL.NS",
  "IKS.NS", "IPCALAB.NS", "JBCHEPHARM.NS", "JKCEMENT.NS", "JBMA.NS", "JKTYRE.NS",
  "JSWCEMENT.NS", "JSWDULUX.NS", "JSWENERGY.NS", "JSWINFRA.NS", "JSWSTEEL.NS", "JAINREC.NS",
  "JPPOWER.NS", "JINDALSAW.NS", "JSL.NS", "JINDALSTEL.NS", "JUBLFOOD.NS", "JUBLINGREA.NS",
  "JUBLPHARMA.NS", "JWL.NS", "JYOTICNC.NS", "KPRMILL.NS", "KEI.NS", "KPITTECH.NS",
  "KAJARIACER.NS", "KPIL.NS", "KALYANKJIL.NS", "KAYNES.NS", "KEC.NS", "KIRLOSENG.NS",
  "KIMS.NS", "LTTS.NS", "LGEINDIA.NS", "LTFOODS.NS", "LTM.NS", "LT.NS",
  "LATENTVIEW.NS", "LAURUSLABS.NS", "THELEELA.NS", "LEMONTREE.NS", "LENSKART.NS", "LINDEINDIA.NS",
  "LLOYDSME.NS", "LODHA.NS", "LUPIN.NS", "MMTC.NS", "MRF.NS", "MGL.NS",
  "M&M.NS", "MRPL.NS", "MANKIND.NS", "MARICO.NS", "MARUTI.NS", "MAXHEALTH.NS",
  "MAZDOCK.NS", "MEESHO.NS", "MINDACORP.NS", "MSUMI.NS", "MPHASIS.NS", "NATCOPHARM.NS",
  "NBCC.NS", "NCC.NS", "NHPC.NS", "NLCINDIA.NS", "NMDC.NS", "NSLNISP.NS",
  "NTPCGREEN.NS", "NTPC.NS", "NH.NS", "NATIONALUM.NS", "NAVA.NS", "NAVINFLUOR.NS",
  "NESTLEIND.NS", "NETWEB.NS", "NEULANDLAB.NS", "NEWGEN.NS", "NUVOCO.NS", "OBEROIRLTY.NS",
  "ONGC.NS", "OIL.NS", "OLAELEC.NS", "OLECTRA.NS", "ONESOURCE.NS", "OFSS.NS",
  "PCBL.NS", "PGEL.NS", "PIIND.NS", "PTCIL.NS", "PAGEIND.NS", "PARADEEP.NS",
  "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS", "PFIZER.NS", "PHOENIXLTD.NS", "PWL.NS",
  "PIDILITIND.NS", "PPLPHARMA.NS", "POLYMED.NS", "POLYCAB.NS", "POWERGRID.NS", "PREMIERENE.NS",
  "PRESTIGE.NS", "RRKABEL.NS", "RHIM.NS", "RITES.NS", "RVNL.NS", "RAILTEL.NS",
  "RAINBOW.NS", "RKFORGE.NS", "REDINGTON.NS", "RELIANCE.NS", "RPOWER.NS", "SJVN.NS",
  "SRF.NS", "SAGILITY.NS", "SAILIFE.NS", "MOTHERSON.NS", "SAPPHIRE.NS", "SARDAEN.NS",
  "SCHAEFFLER.NS", "SCHNEIDER.NS", "SCI.NS", "SHREECEM.NS", "SHYAMMETL.NS", "ENRIN.NS",
  "SIEMENS.NS", "SIGNATURE.NS", "SOBHA.NS", "SOLARINDS.NS", "SONACOMS.NS", "SONATSOFTW.NS",
  "SAIL.NS", "SUMICHEM.NS", "SUNPHARMA.NS", "SUPREMEIND.NS", "SPLPETRO.NS", "SUZLON.NS",
  "SWANCORP.NS", "SWIGGY.NS", "SYNGENE.NS", "SYRMA.NS", "TBOTEK.NS", "TVSMOTOR.NS",
  "TATACHEM.NS", "TATACOMM.NS", "TCS.NS", "TATACONSUM.NS", "TATAELXSI.NS", "TMCV.NS",
  "TMPV.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TATATECH.NS", "TTML.NS", "TECHM.NS",
  "TECHNOE.NS", "TEGA.NS", "TEJASNET.NS", "TENNIND.NS", "RAMCOCEM.NS", "THERMAX.NS",
  "TIMKEN.NS", "TITAGARH.NS", "TITAN.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", "TARIL.NS",
  "TRAVELFOOD.NS", "TRENT.NS", "TRIDENT.NS", "TRITURBINE.NS", "TIINDIA.NS", "UNOMINDA.NS",
  "UPL.NS", "ULTRACEMCO.NS", "URBANCO.NS", "USHAMART.NS", "VTL.NS", "VBL.NS",
  "VEDL.NS", "VIJAYA.NS", "VMM.NS", "IDEA.NS", "VOLTAS.NS", "WAAREEENER.NS",
  "WELCORP.NS", "WELSPUNLIV.NS", "WHIRLPOOL.NS", "WIPRO.NS", "WOCKPHARMA.NS", "ZFCVINDIA.NS",
  "ZENTEC.NS", "ZENSARTECH.NS", "ZYDUSLIFE.NS", "ZYDUSWELL.NS", "ECLERX.NS",
];

export const HALAL_IN_STOCKS = NIFTY_500_SYMBOLS.filter(s => !['HDFCBANK.NS','ICICIBANK.NS','SBIN.NS','KOTAKBANK.NS','AXISBANK.NS','BAJFINANCE.NS','BAJAJFINSV.NS','CHOLAFIN.NS','MUTHOOTFIN.NS','SRTRANSFIN.NS','M&MFIN.NS','HDFCLIFE.NS','SBILIFE.NS','ICICIPRULI.NS','LICHSGFIN.NS','PNB.NS','BANKBARODA.NS','INDUSINDBK.NS','YESBANK.NS','IDFCFIRSTB.NS','BANDHANBNK.NS','FEDERALBNK.NS','AUBANK.NS','HDFCAMC.NS','NAM-INDIA.NS'].includes(s));

export const SECTOR_INDICES = [
  "^NSEBANK", "^CNXAUTO", "^CNXIT", "^CNXPHARMA", "^CNXMETAL", "^CNXFMCG",
  "^CNXREALTY", "^CNXENERGY", "^CNXINFRA", "^CNXMEDIA", "^CNXPSE", "^CNXPSUBANK", "^CNXFIN"
];

export const SECTOR_CONSTITUENTS: Record<string, string[]> = {
  "^NSEBANK": ["HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "SBIN.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "AUBANK.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS", "PNB.NS", "BANDHANBNK.NS"],
  "^CNXAUTO": ["M&M.NS", "MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "TVSMOTOR.NS", "ASHOKLEY.NS", "MOTHERSON.NS", "BALKRISIND.NS", "BOSCHLTD.NS", "MRF.NS", "TIINDIA.NS", "SONACOMS.NS", "BHARATFORG.NS"],
  "^CNXIT": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS"],
  "^CNXPHARMA": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS", "AUROPHARMA.NS", "TORNTPHARM.NS", "ALKEM.NS", "ZYDUSLIFE.NS", "ABBOTINDIA.NS", "BIOCON.NS", "GLENMARK.NS", "LAURUSLABS.NS", "SYNGENE.NS", "GRANULES.NS"],
  "^CNXMETAL": ["TATASTEEL.NS", "HINDALCO.NS", "JSWSTEEL.NS", "COALINDIA.NS", "ADANIENT.NS", "VEDL.NS", "JINDALSTEL.NS", "NMDC.NS", "SAIL.NS", "NATIONALUM.NS", "HINDZINC.NS", "APLAPOLLO.NS", "RATNAMANI.NS", "WELCORP.NS", "HINDCOPPER.NS"],
  "^CNXFMCG": ["ITC.NS", "HUL.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TATACONSUM.NS", "GODREJCP.NS", "DABUR.NS", "MARICO.NS", "UBL.NS", "MCDOWELL-N.NS", "COLPAL.NS", "PGHH.NS", "EMAMILTD.NS", "RADICO.NS", "BALRAMCHIN.NS"],
  "^CNXREALTY": ["DLF.NS", "MACROTECH.NS", "GODREJPROP.NS", "PRESTIGE.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "BRIGADE.NS", "SOBHA.NS", "MAHLIFE.NS", "PURVA.NS", "SUNTECK.NS", "IBREALEST.NS"],
  "^CNXENERGY": ["RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "COALINDIA.NS", "TATAPOWER.NS", "ADANIGREEN.NS", "ADANIENSOL.NS", "IOC.NS", "BPCL.NS", "GAIL.NS", "HPCL.NS", "PETRONET.NS", "IGL.NS", "MGL.NS"],
  "^CNXINFRA": ["L&T.NS", "RELIANCE.NS", "BHARTIARTL.NS", "NTPC.NS", "POWERGRID.NS", "ULTRACEMCO.NS", "ADANIPORTS.NS", "GRASIM.NS", "INDIGO.NS", "SHREECEM.NS", "AMBUJACEM.NS", "ACC.NS", "VOLTAS.NS", "SIEMENS.NS", "CUMMINSIND.NS"],
  "^CNXMEDIA": ["ZEEL.NS", "SUNTV.NS", "PVRINOX.NS", "NETWORK18.NS", "TV18BRDCST.NS", "NDTV.NS", "NAVNETEDUL.NS", "HATHWAY.NS", "SAREGAMA.NS"],
  "^CNXPSE": ["NTPC.NS", "ONGC.NS", "POWERGRID.NS", "COALINDIA.NS", "HAL.NS", "BEL.NS", "PFC.NS", "RECLTD.NS", "GAIL.NS", "IOC.NS", "BPCL.NS", "NHPC.NS", "OIL.NS", "NMDC.NS", "BHEL.NS", "SAIL.NS", "IRCTC.NS", "MAZDOCK.NS"],
  "^CNXPSUBANK": ["SBIN.NS", "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS", "INDIANB.NS", "BANKINDIA.NS", "MAHABANK.NS", "CENTRALBK.NS", "IOB.NS", "UCOBANK.NS", "PSB.NS"],
  "^CNXFIN": ["HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "SBIN.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "MUTHOOTFIN.NS", "SHRIRAMFIN.NS", "HDFCLIFE.NS", "SBILIFE.NS", "ICICIPRULI.NS", "LOMBARD.NS"]
};

export interface WatchlistItem {
  symbol: string;
  name: string;
  addedDate: number; // timestamp
  addedPrice: number;
  currentPrice?: number;
  targetPrice?: number;
  stopLoss?: number;
}

export interface DailyData {
  time: number; // unix timestamp in seconds
  close: number;
}

export interface WeeklyBar {
  time: string; // "YYYY-MM-DD" inside chart
  timestamp: number; // for sorting/math
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface ScanResult {
  symbol: string;
  name: string;
  passed: boolean;
  weeklyClose: number;
  ema20: number;
  ema50: number;
  ema100: number;
  ema200: number;
  ema30: number;
  ema40: number;
  sma9?: number;
  rsValue: number;
  rsEma: number;
  sangamPassed: boolean;
  sangam2Passed: boolean;
  reversalPassed: boolean;
  rsBoPassed: boolean;
  rsMomPassed: boolean;
  sectorRsPassed: boolean;
  mtfRsPassed: boolean;
  rs52wPassed: boolean;
  mansfieldPassed: boolean;
  minerviniPassed: boolean;
  insideBarPassed: boolean;
  todayChange: number;
  volume: number;
  sector?: string;
  dynamicSl?: number;
  riskPct?: number;
  targetPrice?: number;
  rewardRiskRatio?: number;
  weeklyBars: WeeklyBar[];
  dailyRs: DailyData[];
  dailyRsEma: DailyData[];
  ema20Series: DailyData[];
  ema30Series: DailyData[];
  ema40Series: DailyData[];
  sma9Series: DailyData[];
  ema50Series: DailyData[];
  ema100Series: DailyData[];
  ema200Series: DailyData[];
}
